# https://taskfile.dev

version: '3'

tasks:
  
  test:
    cmds:
      - go test ./...
    silent: true

  coverage:
    desc: Print app test coverage
    cmds:
      - "go test ./... -coverprofile=cover.out >/dev/null 2>&1 && go tool cover -func=cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}' | xargs printf 'Total Coverage: %.1f%%'"
      - echo " "
    silent: true
