# https://taskfile.dev

version: '3'

vars:
  # Homebrew paths for Tesseract/Leptonica on Apple Silicon
  CGO_CPPFLAGS: "-I/opt/homebrew/include"
  CGO_LDFLAGS: "-L/opt/homebrew/lib"

tasks:

  build:
    desc: Build all packages
    cmds:
      - go build ./...
    env:
      CGO_CPPFLAGS: "{{.CGO_CPPFLAGS}}"
      CGO_LDFLAGS: "{{.CGO_LDFLAGS}}"
    silent: true

  test:
    desc: Run all tests
    cmds:
      - go test ./...
    env:
      CGO_CPPFLAGS: "{{.CGO_CPPFLAGS}}"
      CGO_LDFLAGS: "{{.CGO_LDFLAGS}}"
    silent: true

  test-ocr:
    desc: Run all tests with OCR support enabled (requires Tesseract)
    cmds:
      - go test -tags ocr ./...
    env:
      CGO_CPPFLAGS: "{{.CGO_CPPFLAGS}}"
      CGO_LDFLAGS: "{{.CGO_LDFLAGS}}"
    silent: true

  coverage:
    desc: Print app test coverage
    cmds:
      - "go test ./... -coverprofile=cover.out >/dev/null 2>&1 && go tool cover -func=cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}' | xargs printf 'Total Coverage: %.1f%%'"
      - echo " "
    env:
      CGO_CPPFLAGS: "{{.CGO_CPPFLAGS}}"
      CGO_LDFLAGS: "{{.CGO_LDFLAGS}}"
    silent: true
