package tabula

import "strings"

// WarningCode identifies the type of warning encountered during PDF processing.
type WarningCode int

const (
	// WarningMessyPDF indicates the PDF exhibits traits of being "messy" or
	// display-oriented (e.g., generated by Word, Quartz, or highly fragmented).
	// Text extraction may still succeed but results might have ordering issues.
	WarningMessyPDF WarningCode = iota

	// WarningOCRFallback indicates that OCR was used to extract text from
	// a scanned page that contained no native PDF text. This typically means
	// the page contains only images (e.g., a scanned document).
	WarningOCRFallback
)

// Warning represents a non-fatal issue encountered during PDF processing.
// Unlike errors, warnings indicate that extraction succeeded but the results
// may be imperfect or require attention.
type Warning struct {
	Code    WarningCode
	Message string
}

// String returns the warning message.
func (w Warning) String() string {
	return w.Message
}

// FormatWarnings returns a human-readable string of all warnings.
// Returns empty string if there are no warnings.
func FormatWarnings(warnings []Warning) string {
	if len(warnings) == 0 {
		return ""
	}
	var msgs []string
	for _, w := range warnings {
		msgs = append(msgs, w.Message)
	}
	return strings.Join(msgs, "; ")
}
